#pragma once

/**
 * @brief calculates the result of the math syntax tree generated by the parser 
 */

#include "cstr.h"
#include "ast.h"
#include "tokens.h"
#include "token_math.h"

cstr *interpret_ast(AstNode *ast);