#pragma once 

/**
 *  @brief parser functions that parse the tokens generated by the lexer and with that creates an Abstract syntax tree
 */

#include "cstr.h"
#include "strvec.h"
#include "lexer.h"
#include "ast.h"
#include "console.h"

Ast *parser(svector *tokens);
void parse_(int i, svector *tokens,  AstNode *node);